filter:
  paths: ["src/*"]
  excluded_paths:
    - "tests/"

build:
  environment:
    php: 7.4
    timezone: Europe/Paris

  nodes:
    tests:
      tests:
        override:
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover
